[package]
name = "cargo-bencher"
version = "0.1.1"
description = "Bencher for Cargo"
homepage = "https://bencher.dev"
repository = "https://github.com/bencherdev/bencher"
readme = "README.md"
license-file = "LICENSE.md"

[dependencies]
