[alias]
xtask = "run --manifest-path ./xtask/Cargo.toml --"
# Tasks
bin-version = "run --manifest-path ./tasks/bin_version/Cargo.toml --"
gen-installer = "run --manifest-path ./tasks/gen_installer/Cargo.toml --"
gen-pkg = "run --manifest-path ./tasks/gen_pkg/Cargo.toml --"
gen-notes = "run --manifest-path ./tasks/gen_notes/Cargo.toml --"
gen-spec = "run --manifest-path ./tasks/gen_types/Cargo.toml -- spec"
gen-ts = "run --manifest-path ./tasks/gen_types/Cargo.toml -- ts"
gen-types = "run --manifest-path ./tasks/gen_types/Cargo.toml -- types"
test-api = "run --manifest-path ./tasks/test_api/Cargo.toml --"
test-netlify = "run --manifest-path ./tasks/test_netlify/Cargo.toml --"
