[package]
name = "bencher_api"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[features]
default = ["plus", "sentry"]
plus = [
    "bencher_json/plus",
    "bencher_schema/plus",
    "dep:bencher_billing",
    "dep:bencher_github",
    "dep:bencher_license",
]
sentry = ["bencher_schema/sentry", "dep:sentry"]

[dependencies]
# Workspace
bencher_billing = { workspace = true, optional = true }
bencher_endpoint.workspace = true
bencher_github = { workspace = true, optional = true }
bencher_json = { workspace = true, features = ["server", "schema", "db"] }
bencher_license = { workspace = true, optional = true }
bencher_logger.workspace = true
bencher_plot.workspace = true
bencher_rbac.workspace = true
bencher_schema.workspace = true
bencher_token.workspace = true
chrono.workspace = true
diesel = { workspace = true, features = ["chrono", "sqlite"] }
dropshot.workspace = true
http.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
oso.workspace = true
slog.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "rt-multi-thread"] }
tokio-rustls.workspace = true
url.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
# Crate
async-compression = { version = "0.4", features = ["tokio", "gzip"] }
sentry = { version = "0.36", optional = true, default-features = false, features = [
    "reqwest",
    "rustls",
] }

# https://github.com/diesel-rs/diesel/blob/ba2f567b038179d16cea939c0bcaaecc216ea947/diesel/Cargo.toml#L19
# https://github.com/tauri-apps/tauri/discussions/6183
# Always needed for Windows and all other targets when building a distroless image
[dependencies.libsqlite3-sys]
version = ">=0.17.2, <0.31.0"
features = ["bundled"]

[lints]
workspace = true

[[bin]]
name = "api"
path = "src/main.rs"
