[package]
name = "bencher_license"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[dependencies]
# Workspace
bencher_json = { workspace = true, features = ["server", "plus"] }
chrono.workspace = true
jsonwebtoken = { workspace = true, features = ["use_pem"] }
thiserror.workspace = true
serde.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true

[lints]
workspace = true
