[package]
name = "bencher_bing_index"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[dependencies]
reqwest = { workspace = true, features = ["rustls-tls"] }
thiserror.workspace = true
url = { workspace = true, features = ["serde"] }

[lints]
workspace = true
